### ISSUE TITLE
Problem with modifying frozen strings

### ISSUE THREAD

**Issue by elliotcm** [DFE-Digital/govuk-markdown#26]
The [new preprocessor](https://github.com/DFE-Digital/govuk-markdown/compare/v1.0.0...v2.0.0#diff-a9b93a1fee31172176e185c9438524ac498d5be03d101c4c6d4a80605f76ad25R10) attempts to modify strings in-place, which doesn't play well when fed frozen strings (such as the ones from Apply's API documentation).

Could we modify the preprocessor to avoid trying to modify frozen strings, or perhaps not use the in-place string modifications?

See https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/4190232644/jobs/7263553219

**Comment by HettieS** [comment]
I'll have a look at getting this fixed up soon! @elliotcm
